### ISSUE TITLE
skillchains functions throw lua runtime error

### ISSUE THREAD

**Issue by gammaleak** [AliekberFFXI/xivcrossbar#1]
Attempted a first-time install. As soon as Windower loaded the addon it began spewing lua runtime errors on two lines:

- Predominantly xivcrossbar/xivcrossbar.lua:766 "prerender" is not defined for booleans
- Also sometimes: xivcrossbar/xivcrossbar.lua:839 "incoming_chunk" is not defined for booleans

The initial setup dialog also did not recognize any of my button presses (Windower was launched as Administrator), however, I thought that this might just be due to the lua scripts failing.

**Comment by gammaleak** [comment]
I wondered if maybe your changes on Oct 7 to add frameskipping may have introduced this problem, so I downloaded the code as it existed eod Oct 6. Unfortunately, this problem still persisted.

**Comment by AliekberFFXI** [comment]
So, you'll need to make sure that the AutoHotKey is running as Administrator as well, but the stranger part is the error message you're seeing, because it implies that the skillchain lib object is actually a boolean somehow. Can you post your skillchains lua? (addons/xivcrossbar/libs/skillchani/skillchains.lua)

**Comment by AliekberFFXI** [comment]
@gammaleak ^

**Comment by gammaleak** [comment]
I uninstalled it back in November when I first tried and it didn't work. Just tried a re-install using the latest code and got the exact same results. I cannot tell if Autohotkey is running in Administrator mode or not. If I just try to "run Autohotkey" it just brings up a Help page and tells me I tried to run it without a script and that doesn't work (sorry, I have zero experience with AHK).

**Comment by AliekberFFXI** [comment]
Ah, ok. Basically, you have to go to windower/addons/xivcrossbar, then right-click on ffxi_directinput.ahk and select "Run as Administrator", then do the same to ffxi_xinput.ahk.

With all that said, I'm still really confused as to how you're getting this runtime error. How are you starting the addon?

**Comment by gammaleak** [comment]
Here's what I'm doing:
1. Download the repository as a zip file to my Downloads directory and unzip it
2. Remove the "-master" appended to the name of the folder (from the way github names the download) so that the name of the folder is "xivcrossbar"
3. Move the folder to Windower's "addons" directory
4. Modify init.txt to load the addon with "lua load xivcrossbar"

And that's it. Tonight I can try to start both those scripts before launching the game and see if that changes anything.

One other note: I don't have Gearswap installed as I'm pretty newb at the game and don't have any jobs at iLvl119, so it seems sort of unnecessary at this point. But maybe that's a hidden dependency here?

**Comment by AliekberFFXI** [comment]
Yeah, it looks like the skillchains lib doesn't like being loaded before the player is logged in. I've pushed an update, which I think will work for you.

**Comment by gammaleak** [comment]
It does seem that I have to manually launch both of those AHK scripts, but your fix got rid of the runtime error. Thank you!
