### ISSUE TITLE
Bug: settings files randomly erase

### ISSUE THREAD

**Issue by beerman212** [AliekberFFXI/xivcrossbar#10]
I'm not sure what actually causes this, but it's happened to me a number of times where the all-jobs-default, and the jobname-default files get completely cleared out.  It's multiple times erased significant work as I try to configure a complex job (RDM) and then everything is gone and I have to start over from scratch.

I'm not sure I can duplicate, but I think it had something to do with creating new hotbars on this last time it happened for me.

I made a sword hotbar for my rdm, and then all of my rdm-default and all-jobs-default xmls were empty.

**Comment by AliekberFFXI** [comment]
Crap, I thought I'd fixed this bug. I'll take a look when I get the chance.

**Comment by AliekberFFXI** [comment]
Ok, found how it was happening. Should be fixed now. Please reopen this bug if it happens again with the latest version.
