### ISSUE TITLE
mount roulette error 

### ISSUE THREAD

**Issue by DrZapper112** [AliekberFFXI/xivcrossbar#12]
I've been using your addon for a long time now with no issues. I never even use mount roulette. Today when i loaded the game up I can not get xivcrossbar to load at all.  I'll attach a screenshot of the error i am getting. Any help is greatly appreciated. Thanks
![ffxi](https://user-images.githubusercontent.com/91566246/184963711-82f9587e-ae56-47d6-a0ed-2a1a75c3f872.jpg)
.

**Comment by AliekberFFXI** [comment]
Just pushed a fix. Can you verify that the issue no longer occurs?

**Comment by DrZapper112** [comment]
That did the trick! Thank you so much for your help.

**Comment by AliekberFFXI** [comment]
No problem. Glad to hear it's working again.
