### ISSUE TITLE
consumables error

### ISSUE THREAD

**Issue by DrZapper112** [AliekberFFXI/xivcrossbar#13]
Hi, I'm sorry to bother you again. After that last update to the mount roulette i'm getting some new errors. The addon is working but i constantly get these errors on my screen. Thanks again
![Untitled](https://user-images.githubusercontent.com/91566246/185190985-7996a307-6ebb-43c8-8c49-cf14b6a51273.jpg)

**Comment by AliekberFFXI** [comment]
No problem at all. I've pushed a fix. Can you verify that it's working for you?

**Comment by AliekberFFXI** [comment]
Closing as fixed due to lack of response.
