### ISSUE TITLE
JA Dependency on Rune Enchantments 

### ISSUE THREAD

**Issue by SkroneTone** [AliekberFFXI/xivcrossbar#3]
First off, this is an awesome addon! It’s already streamlined my play style so much, and I really appreciate it! I just have one question about JA cooldowns. I play RUN a lot and the Rune spells like Ignis and Gelus are dependent on the Rune Enchantment cooldown timer. Current state, if I use one of those abilities in the addon, the ability goes off, but due to the dependency there is no cooldown set to the hotbar icons for those runes. The ideal functionality would be if any Rune spell is cast, all eight rune spells are given the 5 second cooldown timer. If there’s a way to link their cooldown attributes to the Rune Enchantment JA that may be the easiest way.

**Comment by AliekberFFXI** [comment]
Thanks!

I've been having some computer trouble, but I should be able to take a look at this tomorrow.

**Comment by AliekberFFXI** [comment]
So, I tried to replicate your issue, but I couldn't. Whenever I use (e.g.) Ignis, it also starts the recast timer for Gelus, Flabra, etc. All 8 sync up just the way you'd want them to.

Can you give some more information about what's happening, and add screenshots of the UI (and the Windower console log if it's showing any errors)?

**Comment by AliekberFFXI** [comment]
@SkroneTone ^ Not sure if it automatically notifies you, so I thought I'd mention you in case you had any more information.

**Comment by SkroneTone** [comment]
I’m gonna assume this is something on my end, I’ll try a fresh install and see if that helps.

**Comment by AliekberFFXI** [comment]
Closing as resolved since it's been >1 year.
