### ISSUE TITLE
Icydeath's AHK: certain buttons occasionally double-press

### ISSUE THREAD

**Issue by AliekberFFXI** [AliekberFFXI/xivcrossbar#4]
When using Icydeath's AHK, some users are seeing an issue where actions mapped to face buttons will sometimes fire multiple times in a row during a single press. If you're seeing this issue, please respond with the following information to help me nail down the cause and provide a fix:

Addon version: **[0.1 or 0.1.2i]**
Which AHK are you using? **[Original or Icydeath version]**
Controller type: **[DirectInput, XInput, or Don't Know]**
What buttons are affected? **[List of affected buttons]**
Do the buttons double-press only in XIVCrossbar's menus, only in native FFXI menus, or in both? **[XIVCrossbar, native FFXI, or both]**
How often does the issue occur? **[e.g. 5 times per minute, 1 time per 10 minutes, etc.]**
Does the issue occur more often in certain gameplay events or zones? If so, which ones? **[List of game events/areas]**

**Comment by Icydeath** [comment]
I'll do some investigation as well.

**Comment by Kingdomhearts-FFXI** [comment]
Addon version: [0.1 or 0.1.2i] -1.0
Which AHK are you using? [Original or Icydeath version] -Icydeath
Controller type: [DirectInput, XInput, or Don't Know] -XInput
What buttons are affected? [List of affected buttons] -Square and X on a PS3 Afterglow wireless controller are the only ones I've noticed.
Do the buttons double-press only in XIVCrossbar's menus, only in native FFXI menus, or in both? [XIVCrossbar, native FFXI, or both] -FFXI Menus only
How often does the issue occur? [e.g. 5 times per minute, 1 time per 10 minutes, etc.] -5 or more times a minute
Does the issue occur more often in certain gameplay events or zones? If so, which ones? [List of game events/areas] **-I have not noticed it occurring anywhere more often then another, issue seems to be pretty consistent in all areas**

I also made a video, if that helps of the issue. If you notice when I open the main menu, it'll sometimes stay on the same page. Best way to describe that is it should go from the page with "Party" listed to the one with "Config" listed. But when I push the square button, it'll flash and remain on the same page as it was in, as if it's the square button was pressed twice rapidly. Also when I click on the door to exit the Mog House, it'll automatically select "Stay in your room." before the menu even fully appears and exit out of the menu.

https://youtu.be/Wm_5CUh7ebg 

Sorry this has been such an issue, but I want you both to know I really appreciate the help and the effort made in creating this addon..

**Comment by AliekberFFXI** [comment]
Well, I did some testing tonight with an XInput controller and Icydeath's AHK, but I'm still unable to reproduce the double-press bug. I understand the reason for the targeting glitch now that I've thought about it, but it still doesn't make sense why the fix for it would cause this bug. Not giving up, but no real progress yet, either.

**Comment by Kingdomhearts-FFXI** [comment]
I may have figured it out, somewhat hoping my suspicions are not true because it would mean this is an ID10T error. At one point, while you were busy with RL Aliek, I had download Icy's updated version of crossbar and just copy and pasted it into my addon folder. My guess is, it wasn't a clean update(some of the original files weren't overwritten and remained) and that caused a conflict that resulted in the double-press bug. I just reinstalled the addon from square one, copied over my settings, and now I'm no longer experiencing the problem. I have the next three days off from work and will test it to ensure I'm good to go and then report back. If that's all it was, I feel really stupid for the effort you two have put in to look into the matter for nothing, but I am extremely grateful. Will let you know how the addon performs from here on.

**Comment by Icydeath** [comment]
I'm just happy you were able to get it working :D. Enjoy!

**Comment by Kingdomhearts-FFXI** [comment]
Just wanted to say, I've been playing XI using the addon for the past day or so and so far, the bug has not reappeared, so I'm going to assume it's been resolved. Want to thank you both again for your help.

**Comment by AliekberFFXI** [comment]
Great! Glad to hear it.
