### ISSUE TITLE
I can't map Strategems on whm/sch

### ISSUE THREAD

**Issue by beerman212** [AliekberFFXI/xivcrossbar#5]
I get the following error when I select strategems in the menu on whm/sch.

"xivcrossbar: Lua runtime error: xivcrossbar/action_binder.lua:13: attempt to index local 'str' (a nil value)"

I'm not sure what's happening, or why it's firing off other than it doesn't like me selecting strategems from the menu.

**Comment by AliekberFFXI** [comment]
Fixed!
