### ISSUE TITLE
Run plugin is required

### ISSUE THREAD

**Issue by KevinSShaffer** [AliekberFFXI/xivcrossbar#6]
Please edit the readme.md to include the Run plugin as a dependency.  I think this will solve the "run as administrator" issues I found in the ffxiah.com post.

> Usually this is due to needing to run your AHK scripts as Administrator. If Windower is running as Administrator, then they should be automatically run as Administrator as well (the addon starts the AHK scripts each time it loads), but if they aren't, manually doing so should fix things.

**Comment by AliekberFFXI** [comment]
Done!
