### ISSUE TITLE
Unable to select Pet Command when on Summoner.

### ISSUE THREAD

**Issue by mtrjohns** [AliekberFFXI/xivcrossbar#8]
Unable to select Pet Command when on Summoner.

"xivcrossbar: Lua runtime error: xivcrossbar/action_binder.lua:13: attempt to index local 'str' (a nil value)"

Pet Command menu shows as a blank page with no selectable icons to bind to crossbar.

**Comment by AliekberFFXI** [comment]
Fixed!
